### PR TITLE
orders_fetch

### PR DESCRIPTION
**Pull request by 0xC0rv0**
fetching orders from order API end point 

orders

### CODE REVIEW

**Comment by shahwan42** [comment]
For each product id get the product details from its api and show its info in a better and more understandable way

**Comment by 0xC0rv0** [comment]
image

**Comment by shahwan42** [comment]
Make the ci pass

**Comment by 0xC0rv0** [comment]
@shahwan42  @Mohamed-sattar  
please check the screen , code and accept if there Is not changes required 
product details will be implemented after back-end team finishes the endpoint integrations

**Pull request merged**
